let diccionario = {
    "marka": "provincia",
    "kutin": "en cambio",
    "hampikmi": "médico",
    "uchilla": "pequeño",
    "yachachik": "profesora",
    "yachakuk": "estudiante",
    "unkushka": "enfermo",
    "michik": "pastor",
    "yachak": "el conocedor",
    "shuwak": "ladrón",
    "kuri pisku": "pájaro de oro",
    "runa": "hombre",
    "warmi": "mujer",
    "taksak": "lavadero",
    "mushuk": "nuevo",
    "kunuk": "caliente",
    "yaku": "agua",
    "chiri": "frío",
    "siki": "nalga",
    "wiksayuk": "embarazada",
    "shaykushka": "cansado",
    "hatun": "grande",
    "ña": "ya",
    "wichkana": "cerrar",
    "paskana": "abrir",
    "shuktak": "otra",
    "makikuta": "manita",
    "tushuchini": "la hago bailar",
    "kancha": "estadio/ patio/ espacio exterior",
    "llakta": "pueblo",
    "llakilla": "triste nomás",
    "kushilla": "alegre nomás",
    "chaymanta": "de ese lugar/ de allá/ por eso",
    "chaypi": "allá/ en ese lugar",
    "llama": "oveja",
    "runa llama": "llama",
    "kamak": "cuidador",
    "punku": "puerta",
    "puncha": "día",
    "kaymanta": "de este lugar",
    "shaykushka": "cansado",
    "shinapash": "sin embargo",
    "tuta": "noche",
    "atallpa": "gallina",
    "wacha": "sábado",
    "pacha": "tiempo",
    "chillina": "naranja",
    "kuyashka": "amante / novio",
    "chayshuk": "se otro/ese otra/ aquel otro",
    "rumpa": "elota/ círculo",
    "nina": "fuego",
    "pacari": "amanecer",
    "tiyupa": "don",
    "yayamama": "padres",
    "mishki": "dulce",
    "kunkuri": "rodilla",
    "sumak": "bonito/bello/delicioso/ distinguido",
    "jayka": "¡ten! ¡toma!",
    "sawarishka": "casado",
    "kuyaylla": "bonito",
    "pi": "ubicación",
    "yanuk": "cocinero",
    "kipa": "luego/ bocina/ menor",
    "sapalla": "solo/ soltera",
    "chayshuk": "se otro a",
    "shinaka": "por lo tanto",
    "imatak kan? kaywan": "¿qué es?",
    "killkakatina": "lectura",
    "llullu": "bebé",
    "llulla": "mentirosa",
    "tulpu": "color",
    "puka": "rojo",
    "shina": "ejemplo",
    "raymi": "concierto",
    "chuya": "limpio",
    "uku": "dentro",
    "mapa": "sucia",
    "chuklla": "choza",
    "chisi": "tarde",
    "kunanka": "hoy",
    "riksish": "conocido",
    "yara": "arbusto",
    "llantu": "sombra",
    "llamkay": "trabajo",
    "sara chakra": "cultivo de maíz",
    "pukru": "meseta",
    "chimpa": "al frente",
    "tantarakay": "reunión",
    "sacha": "bosque",
    "malto": "mediano",
    "wayna": "auxiliar- amante",
    "kuyak": "amante",
    "machana yakuta": "alcohol",
    "rumpawan": "pelota",
    "wata": "años",
    "irkiyana": "debilitarse",
    "kunan": "ahora",
    "tukuy": "todos",
    "hampik wasic": "centro de salud",
    "utka": "pronto",
    "ña": "al instante",
    "uku": "por dentro/ cuarto",
    "hampina ukuman": "consultorio",
    "ayllukuna": "parientes",
    "nishpa": "decir",
    "shimi": "boca",
    "chay kipa": "luego de eso",
    "samay": "energía/ aire",
    "sirka": "presión",
    "ama": "prohibición",
    "kucha": "río",
    "kuchu": "cerca de cercanía",
    "wayrachina": "ventiladores abanicos",
    "yanta": "leña",
    "imachik": "verbo (el que hacer algo)",
    "kana": "ser o estar",
    "purina": "caminar",
    "mikuna": "comer",
    "charina": "tener",
    "na": "vivir",
    "unkuna": "enfermar",
    "llamkana": "trabajar",
    "yachakuna": "estudiar",
    "yachachina": "enseñar",
    "hampina": "curar",
    "rina": "ir / viajar",
    "michina": "pastar",
    "tsakmana": "desmontar/ arar la tierra con las manos",
    "hallmana": "deshierbar",
    "pukllana": "jugar",
    "tushuna": "bailar",
    "yachana": "conocer/ saber",
    "takina": "hacer música/ tocar instrumentos",
    "hapina": "coger/ captar- agarrar",
    "uyana": "escuchar",
    "killkana": "escribir",
    "muskuna": "soñar",
    "upyana": "beber",
    "kallpana": "correr",
    "munana": "querer",
    "kuyana": "amar",
    "wakana": "llorar",
    "asina": "reír",
    "yanuna": "cocinar",
    "pawana": "saltar y volar",
    "shuwana": "robar",
    "napana": "saludar",
    "shamuna": "venir",
    "chayana": "llegar",
    "shuyana": "esperar/ ser paciente",
    "takshana": "lavar ropa",
    "tarpuna": "sembrar",
    "kamana": "cuidar",
    "pichana": "barrer/ trapear/ borrar/ limpiar",
    "yapuna": "arar",
    "muchana": "muchar",
    "ukllana": "abrazar",
    "kichwashim": "idioma kichwa",
    "riksina": "conocer",
    "sanana": "descansar",
    "kayana": "llamar",
    "karana": "dar",
    "machana": "embriagar",
    "rikuchina": "indicar",
    "nina": "decir",
    "hatarina": "levantarse",
    "tapuna": "preguntar",
    "paskana": "abrir",
    "surkuna": "sacar algo dependiente de mí",
    "llukchina": "sacar algo independiente a mí",
    "wacho": "surcos/ canaleta",
    "rurana": "hacer/ realizar",
    "rantina": "comprar",
    "hatuna": "vender"
};

function agregarPalabra() {
    const espanol = document.getElementById("espanol").value.toLowerCase();
    const quichuwa = document.getElementById("quichuwa").value.toLowerCase();
    const mensaje = document.getElementById("mensaje");

    if (espanol in diccionario || quichuwa in diccionario) {
        mensaje.textContent = "Error: La palabra ya existe en el diccionario.";
    } else if (espanol !== "" && quichuwa !== "") {
        diccionario[espanol] = quichuwa;
        mensaje.textContent = "Palabra agregada con éxito.";
    } else {
        mensaje.textContent = "Error: Por favor, ingrese ambas palabras.";
    }
}

function traducirPalabra() {
    const palabra = document.getElementById("palabra-a-traducir").value.toLowerCase();
    const mensaje = document.getElementById("mensaje");

    if (palabra in diccionario) {
        mensaje.textContent = `Traducción: ${diccionario[palabra]}`;
    } else if (Object.values(diccionario).includes(palabra)) {
        mensaje.textContent = `Traducción: ${Object.keys(diccionario).find(key => diccionario[key] === palabra)}`;
    } else {
        mensaje.textContent = "Error: La palabra no existe en el diccionario.";
    }
}